%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'LTV1';
M_.dynare_version = '4.5.6';
oo_.dynare_version = '4.5.6';
options_.dynare_version = '4.5.6';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('LTV1.log');
M_.exo_names = 'epsiA';
M_.exo_names_tex = 'epsiA';
M_.exo_names_long = 'epsiA';
M_.exo_names = char(M_.exo_names, 'epsiJ');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiJ');
M_.exo_names_long = char(M_.exo_names_long, 'epsiJ');
M_.exo_names = char(M_.exo_names, 'epsiK');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiK');
M_.exo_names_long = char(M_.exo_names_long, 'epsiK');
M_.exo_names = char(M_.exo_names, 'epsiSe');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiSe');
M_.exo_names_long = char(M_.exo_names_long, 'epsiSe');
M_.exo_names = char(M_.exo_names, 'epsiSm');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiSm');
M_.exo_names_long = char(M_.exo_names_long, 'epsiSm');
M_.exo_names = char(M_.exo_names, 'epsiSF');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiSF');
M_.exo_names_long = char(M_.exo_names_long, 'epsiSF');
M_.exo_names = char(M_.exo_names, 'epsiSH');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiSH');
M_.exo_names_long = char(M_.exo_names_long, 'epsiSH');
M_.exo_names = char(M_.exo_names, 'epsiWb');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiWb');
M_.exo_names_long = char(M_.exo_names_long, 'epsiWb');
M_.exo_names = char(M_.exo_names, 'epsiWe');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiWe');
M_.exo_names_long = char(M_.exo_names_long, 'epsiWe');
M_.exo_names = char(M_.exo_names, 'epsiH');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiH');
M_.exo_names_long = char(M_.exo_names_long, 'epsiH');
M_.exo_names = char(M_.exo_names, 'epsiHd');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiHd');
M_.exo_names_long = char(M_.exo_names_long, 'epsiHd');
M_.exo_names = char(M_.exo_names, 'epsiHk');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiHk');
M_.exo_names_long = char(M_.exo_names_long, 'epsiHk');
M_.exo_names = char(M_.exo_names, 'epsilon_phi');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilon\_phi');
M_.exo_names_long = char(M_.exo_names_long, 'epsilon_phi');
M_.endo_names = 'b_e';
M_.endo_names_tex = 'b\_e';
M_.endo_names_long = 'b_e';
M_.endo_names = char(M_.endo_names, 'g_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_H');
M_.endo_names_long = char(M_.endo_names_long, 'g_H');
M_.endo_names = char(M_.endo_names, 'g_H_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_H\_1');
M_.endo_names_long = char(M_.endo_names_long, 'g_H_1');
M_.endo_names = char(M_.endo_names, 'IH');
M_.endo_names_tex = char(M_.endo_names_tex, 'IH');
M_.endo_names_long = char(M_.endo_names_long, 'IH');
M_.endo_names = char(M_.endo_names, 'PH');
M_.endo_names_tex = char(M_.endo_names_tex, 'PH');
M_.endo_names_long = char(M_.endo_names_long, 'PH');
M_.endo_names = char(M_.endo_names, 'A');
M_.endo_names_tex = char(M_.endo_names_tex, 'A');
M_.endo_names_long = char(M_.endo_names_long, 'A');
M_.endo_names = char(M_.endo_names, 'b_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_m');
M_.endo_names_long = char(M_.endo_names_long, 'b_m');
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names_long = char(M_.endo_names_long, 'C');
M_.endo_names = char(M_.endo_names, 'C_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_m');
M_.endo_names_long = char(M_.endo_names_long, 'C_m');
M_.endo_names = char(M_.endo_names, 'C_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_s');
M_.endo_names_long = char(M_.endo_names_long, 'C_s');
M_.endo_names = char(M_.endo_names, 'D');
M_.endo_names_tex = char(M_.endo_names_tex, 'D');
M_.endo_names_long = char(M_.endo_names_long, 'D');
M_.endo_names = char(M_.endo_names, 'def_rate_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'def\_rate\_e');
M_.endo_names_long = char(M_.endo_names_long, 'def_rate_e');
M_.endo_names = char(M_.endo_names, 'def_rate_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'def\_rate\_m');
M_.endo_names_long = char(M_.endo_names_long, 'def_rate_m');
M_.endo_names = char(M_.endo_names, 'def_rate_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'def\_rate\_H');
M_.endo_names_long = char(M_.endo_names_long, 'def_rate_H');
M_.endo_names = char(M_.endo_names, 'def_rate_F');
M_.endo_names_tex = char(M_.endo_names_tex, 'def\_rate\_F');
M_.endo_names_long = char(M_.endo_names_long, 'def_rate_F');
M_.endo_names = char(M_.endo_names, 'epsilonH');
M_.endo_names_tex = char(M_.endo_names_tex, 'epsilonH');
M_.endo_names_long = char(M_.endo_names_long, 'epsilonH');
M_.endo_names = char(M_.endo_names, 'epsilonF');
M_.endo_names_tex = char(M_.endo_names_tex, 'epsilonF');
M_.endo_names_long = char(M_.endo_names_long, 'epsilonF');
M_.endo_names = char(M_.endo_names, 'G_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'G\_e');
M_.endo_names_long = char(M_.endo_names_long, 'G_e');
M_.endo_names = char(M_.endo_names, 'G_e_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'G\_e\_1');
M_.endo_names_long = char(M_.endo_names_long, 'G_e_1');
M_.endo_names = char(M_.endo_names, 'G_F');
M_.endo_names_tex = char(M_.endo_names_tex, 'G\_F');
M_.endo_names_long = char(M_.endo_names_long, 'G_F');
M_.endo_names = char(M_.endo_names, 'F_pF');
M_.endo_names_tex = char(M_.endo_names_tex, 'F\_pF');
M_.endo_names_long = char(M_.endo_names_long, 'F_pF');
M_.endo_names = char(M_.endo_names, 'G_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'G\_H');
M_.endo_names_long = char(M_.endo_names_long, 'G_H');
M_.endo_names = char(M_.endo_names, 'F_pH');
M_.endo_names_tex = char(M_.endo_names_tex, 'F\_pH');
M_.endo_names_long = char(M_.endo_names_long, 'F_pH');
M_.endo_names = char(M_.endo_names, 'g_I');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_I');
M_.endo_names_long = char(M_.endo_names_long, 'g_I');
M_.endo_names = char(M_.endo_names, 'g_I_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_I\_1');
M_.endo_names_long = char(M_.endo_names_long, 'g_I_1');
M_.endo_names = char(M_.endo_names, 'G_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'G\_m');
M_.endo_names_long = char(M_.endo_names_long, 'G_m');
M_.endo_names = char(M_.endo_names, 'G_m_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'G\_m\_1');
M_.endo_names_long = char(M_.endo_names_long, 'G_m_1');
M_.endo_names = char(M_.endo_names, 'Gamma_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gamma\_e');
M_.endo_names_long = char(M_.endo_names_long, 'Gamma_e');
M_.endo_names = char(M_.endo_names, 'Gamma_e_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gamma\_e\_1');
M_.endo_names_long = char(M_.endo_names_long, 'Gamma_e_1');
M_.endo_names = char(M_.endo_names, 'Gamma_F');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gamma\_F');
M_.endo_names_long = char(M_.endo_names_long, 'Gamma_F');
M_.endo_names = char(M_.endo_names, 'Gamma_F_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gamma\_F\_1');
M_.endo_names_long = char(M_.endo_names_long, 'Gamma_F_1');
M_.endo_names = char(M_.endo_names, 'Gamma_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gamma\_H');
M_.endo_names_long = char(M_.endo_names_long, 'Gamma_H');
M_.endo_names = char(M_.endo_names, 'Gamma_H_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gamma\_H\_1');
M_.endo_names_long = char(M_.endo_names_long, 'Gamma_H_1');
M_.endo_names = char(M_.endo_names, 'Gamma_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gamma\_m');
M_.endo_names_long = char(M_.endo_names_long, 'Gamma_m');
M_.endo_names = char(M_.endo_names, 'Gamma_m_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gamma\_m\_1');
M_.endo_names_long = char(M_.endo_names_long, 'Gamma_m_1');
M_.endo_names = char(M_.endo_names, 'F_pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'F\_pi');
M_.endo_names_long = char(M_.endo_names_long, 'F_pi');
M_.endo_names = char(M_.endo_names, 'F_pe');
M_.endo_names_tex = char(M_.endo_names_tex, 'F\_pe');
M_.endo_names_long = char(M_.endo_names_long, 'F_pe');
M_.endo_names = char(M_.endo_names, 'H');
M_.endo_names_tex = char(M_.endo_names_tex, 'H');
M_.endo_names_long = char(M_.endo_names_long, 'H');
M_.endo_names = char(M_.endo_names, 'H_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'H\_m');
M_.endo_names_long = char(M_.endo_names_long, 'H_m');
M_.endo_names = char(M_.endo_names, 'H_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'H\_s');
M_.endo_names_long = char(M_.endo_names_long, 'H_s');
M_.endo_names = char(M_.endo_names, 'I');
M_.endo_names_tex = char(M_.endo_names_tex, 'I');
M_.endo_names_long = char(M_.endo_names_long, 'I');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'L_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'L\_m');
M_.endo_names_long = char(M_.endo_names_long, 'L_m');
M_.endo_names = char(M_.endo_names, 'L_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'L\_s');
M_.endo_names_long = char(M_.endo_names_long, 'L_s');
M_.endo_names = char(M_.endo_names, 'Lambda_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda\_m');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda_m');
M_.endo_names = char(M_.endo_names, 'Lambda_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda\_s');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda_s');
M_.endo_names = char(M_.endo_names, 'n_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_b');
M_.endo_names_long = char(M_.endo_names_long, 'n_b');
M_.endo_names = char(M_.endo_names, 'n_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_e');
M_.endo_names_long = char(M_.endo_names_long, 'n_e');
M_.endo_names = char(M_.endo_names, 'omega_bar_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_bar\_e');
M_.endo_names_long = char(M_.endo_names_long, 'omega_bar_e');
M_.endo_names = char(M_.endo_names, 'omega_bar_F');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_bar\_F');
M_.endo_names_long = char(M_.endo_names_long, 'omega_bar_F');
M_.endo_names = char(M_.endo_names, 'omega_bar_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_bar\_H');
M_.endo_names_long = char(M_.endo_names_long, 'omega_bar_H');
M_.endo_names = char(M_.endo_names, 'omega_bar_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_bar\_m');
M_.endo_names_long = char(M_.endo_names_long, 'omega_bar_m');
M_.endo_names = char(M_.endo_names, 'PI');
M_.endo_names_tex = char(M_.endo_names_tex, 'PI');
M_.endo_names_long = char(M_.endo_names_long, 'PI');
M_.endo_names = char(M_.endo_names, 'q_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_H');
M_.endo_names_long = char(M_.endo_names_long, 'q_H');
M_.endo_names = char(M_.endo_names, 'q_K');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_K');
M_.endo_names_long = char(M_.endo_names_long, 'q_K');
M_.endo_names = char(M_.endo_names, 'R_D');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_D');
M_.endo_names_long = char(M_.endo_names_long, 'R_D');
M_.endo_names = char(M_.endo_names, 'R_F');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_F');
M_.endo_names_long = char(M_.endo_names_long, 'R_F');
M_.endo_names = char(M_.endo_names, 'R_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_H');
M_.endo_names_long = char(M_.endo_names_long, 'R_H');
M_.endo_names = char(M_.endo_names, 'r_K');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_K');
M_.endo_names_long = char(M_.endo_names_long, 'r_K');
M_.endo_names = char(M_.endo_names, 'R_K');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_K');
M_.endo_names_long = char(M_.endo_names_long, 'R_K');
M_.endo_names = char(M_.endo_names, 'R_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_m');
M_.endo_names_long = char(M_.endo_names_long, 'R_m');
M_.endo_names = char(M_.endo_names, 'R_tilde_F');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_tilde\_F');
M_.endo_names_long = char(M_.endo_names_long, 'R_tilde_F');
M_.endo_names = char(M_.endo_names, 'R_tilde_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_tilde\_H');
M_.endo_names_long = char(M_.endo_names_long, 'R_tilde_H');
M_.endo_names = char(M_.endo_names, 'Tr_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'Tr\_H');
M_.endo_names_long = char(M_.endo_names_long, 'Tr_H');
M_.endo_names = char(M_.endo_names, 'Tr_F');
M_.endo_names_tex = char(M_.endo_names_tex, 'Tr\_F');
M_.endo_names_long = char(M_.endo_names_long, 'Tr_F');
M_.endo_names = char(M_.endo_names, 'Tr');
M_.endo_names_tex = char(M_.endo_names_tex, 'Tr');
M_.endo_names_long = char(M_.endo_names_long, 'Tr');
M_.endo_names = char(M_.endo_names, 'UC_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'UC\_m');
M_.endo_names_long = char(M_.endo_names_long, 'UC_m');
M_.endo_names = char(M_.endo_names, 'UC_m_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'UC\_m\_1');
M_.endo_names_long = char(M_.endo_names_long, 'UC_m_1');
M_.endo_names = char(M_.endo_names, 'UC_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'UC\_s');
M_.endo_names_long = char(M_.endo_names_long, 'UC_s');
M_.endo_names = char(M_.endo_names, 'UC_s_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'UC\_s\_1');
M_.endo_names_long = char(M_.endo_names_long, 'UC_s_1');
M_.endo_names = char(M_.endo_names, 'UH_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'UH\_m');
M_.endo_names_long = char(M_.endo_names_long, 'UH_m');
M_.endo_names = char(M_.endo_names, 'UH_m_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'UH\_m\_1');
M_.endo_names_long = char(M_.endo_names_long, 'UH_m_1');
M_.endo_names = char(M_.endo_names, 'UH_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'UH\_s');
M_.endo_names_long = char(M_.endo_names_long, 'UH_s');
M_.endo_names = char(M_.endo_names, 'UH_s_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'UH\_s\_1');
M_.endo_names_long = char(M_.endo_names_long, 'UH_s_1');
M_.endo_names = char(M_.endo_names, 'UL_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'UL\_m');
M_.endo_names_long = char(M_.endo_names_long, 'UL_m');
M_.endo_names = char(M_.endo_names, 'UL_m_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'UL\_m\_1');
M_.endo_names_long = char(M_.endo_names_long, 'UL_m_1');
M_.endo_names = char(M_.endo_names, 'UL_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'UL\_s');
M_.endo_names_long = char(M_.endo_names_long, 'UL_s');
M_.endo_names = char(M_.endo_names, 'UL_s_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'UL\_s\_1');
M_.endo_names_long = char(M_.endo_names_long, 'UL_s_1');
M_.endo_names = char(M_.endo_names, 'Util_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'Util\_m');
M_.endo_names_long = char(M_.endo_names_long, 'Util_m');
M_.endo_names = char(M_.endo_names, 'Util_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'Util\_s');
M_.endo_names_long = char(M_.endo_names_long, 'Util_s');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'W_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'W\_b');
M_.endo_names_long = char(M_.endo_names_long, 'W_b');
M_.endo_names = char(M_.endo_names, 'Pr_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pr\_H');
M_.endo_names_long = char(M_.endo_names_long, 'Pr_H');
M_.endo_names = char(M_.endo_names, 'W_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'W\_e');
M_.endo_names_long = char(M_.endo_names_long, 'W_e');
M_.endo_names = char(M_.endo_names, 'x_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_e');
M_.endo_names_long = char(M_.endo_names_long, 'x_e');
M_.endo_names = char(M_.endo_names, 'x_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_m');
M_.endo_names_long = char(M_.endo_names_long, 'x_m');
M_.endo_names = char(M_.endo_names, 'xi_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi\_e');
M_.endo_names_long = char(M_.endo_names_long, 'xi_e');
M_.endo_names = char(M_.endo_names, 'xi_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi\_m');
M_.endo_names_long = char(M_.endo_names_long, 'xi_m');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.endo_names = char(M_.endo_names, 'Y_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Y_obs');
M_.endo_names = char(M_.endo_names, 'R_D_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_D\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'R_D_obs');
M_.endo_names = char(M_.endo_names, 'R_m_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_m\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'R_m_obs');
M_.endo_names = char(M_.endo_names, 'R_H_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_H\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'R_H_obs');
M_.endo_names = char(M_.endo_names, 'R_F_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_F\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'R_F_obs');
M_.endo_names = char(M_.endo_names, 'H_m_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'H\_m\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'H_m_obs');
M_.endo_names = char(M_.endo_names, 'H_s_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'H\_s\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'H_s_obs');
M_.endo_names = char(M_.endo_names, 'b_m_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_m\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'b_m_obs');
M_.endo_names = char(M_.endo_names, 'C_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'C_obs');
M_.endo_names = char(M_.endo_names, 'C_m_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_m\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'C_m_obs');
M_.endo_names = char(M_.endo_names, 'C_s_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_s\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'C_s_obs');
M_.endo_names = char(M_.endo_names, 'D_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'D\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'D_obs');
M_.endo_names = char(M_.endo_names, 'I_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'I\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'I_obs');
M_.endo_names = char(M_.endo_names, 'K_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'K\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'K_obs');
M_.endo_names = char(M_.endo_names, 'L_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'L\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'L_obs');
M_.endo_names = char(M_.endo_names, 'L_m_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'L\_m\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'L_m_obs');
M_.endo_names = char(M_.endo_names, 'L_s_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'L\_s\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'L_s_obs');
M_.endo_names = char(M_.endo_names, 'n_b_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_b\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'n_b_obs');
M_.endo_names = char(M_.endo_names, 'n_e_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_e\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'n_e_obs');
M_.endo_names = char(M_.endo_names, 'q_H_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_H\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'q_H_obs');
M_.endo_names = char(M_.endo_names, 'q_K_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_K\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'q_K_obs');
M_.endo_names = char(M_.endo_names, 'r_K_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_K\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'r_K_obs');
M_.endo_names = char(M_.endo_names, 'R_K_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_K\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'R_K_obs');
M_.endo_names = char(M_.endo_names, 'R_tilde_F_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_tilde\_F\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'R_tilde_F_obs');
M_.endo_names = char(M_.endo_names, 'R_tilde_H_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_tilde\_H\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'R_tilde_H_obs');
M_.endo_names = char(M_.endo_names, 'Tr_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Tr\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Tr_obs');
M_.endo_names = char(M_.endo_names, 'w_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'w_obs');
M_.endo_names = char(M_.endo_names, 'x_e_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_e\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'x_e_obs');
M_.endo_names = char(M_.endo_names, 'x_m_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_m\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'x_m_obs');
M_.endo_names = char(M_.endo_names, 'Vs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Vs');
M_.endo_names_long = char(M_.endo_names_long, 'Vs');
M_.endo_names = char(M_.endo_names, 'Vm');
M_.endo_names_tex = char(M_.endo_names_tex, 'Vm');
M_.endo_names_long = char(M_.endo_names_long, 'Vm');
M_.endo_names = char(M_.endo_names, 'Ve');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ve');
M_.endo_names_long = char(M_.endo_names_long, 'Ve');
M_.endo_names = char(M_.endo_names, 'Vb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Vb');
M_.endo_names_long = char(M_.endo_names_long, 'Vb');
M_.endo_names = char(M_.endo_names, 'EJ');
M_.endo_names_tex = char(M_.endo_names_tex, 'EJ');
M_.endo_names_long = char(M_.endo_names_long, 'EJ');
M_.endo_names = char(M_.endo_names, 'EK');
M_.endo_names_tex = char(M_.endo_names_tex, 'EK');
M_.endo_names_long = char(M_.endo_names_long, 'EK');
M_.endo_names = char(M_.endo_names, 'EH');
M_.endo_names_tex = char(M_.endo_names_tex, 'EH');
M_.endo_names_long = char(M_.endo_names_long, 'EH');
M_.endo_names = char(M_.endo_names, 'ESe');
M_.endo_names_tex = char(M_.endo_names_tex, 'ESe');
M_.endo_names_long = char(M_.endo_names_long, 'ESe');
M_.endo_names = char(M_.endo_names, 'ESm');
M_.endo_names_tex = char(M_.endo_names_tex, 'ESm');
M_.endo_names_long = char(M_.endo_names_long, 'ESm');
M_.endo_names = char(M_.endo_names, 'ESH');
M_.endo_names_tex = char(M_.endo_names_tex, 'ESH');
M_.endo_names_long = char(M_.endo_names_long, 'ESH');
M_.endo_names = char(M_.endo_names, 'ESF');
M_.endo_names_tex = char(M_.endo_names_tex, 'ESF');
M_.endo_names_long = char(M_.endo_names_long, 'ESF');
M_.endo_names = char(M_.endo_names, 'EWe');
M_.endo_names_tex = char(M_.endo_names_tex, 'EWe');
M_.endo_names_long = char(M_.endo_names_long, 'EWe');
M_.endo_names = char(M_.endo_names, 'EWb');
M_.endo_names_tex = char(M_.endo_names_tex, 'EWb');
M_.endo_names_long = char(M_.endo_names_long, 'EWb');
M_.endo_names = char(M_.endo_names, 'EdH');
M_.endo_names_tex = char(M_.endo_names_tex, 'EdH');
M_.endo_names_long = char(M_.endo_names_long, 'EdH');
M_.endo_names = char(M_.endo_names, 'EdK');
M_.endo_names_tex = char(M_.endo_names_tex, 'EdK');
M_.endo_names_long = char(M_.endo_names_long, 'EdK');
M_.endo_names = char(M_.endo_names, 'phi_F');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_F');
M_.endo_names_long = char(M_.endo_names_long, 'phi_F');
M_.endo_names = char(M_.endo_names, 'phi_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_H');
M_.endo_names_long = char(M_.endo_names_long, 'phi_H');
M_.endo_names = char(M_.endo_names, 'phi');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi');
M_.endo_names_long = char(M_.endo_names_long, 'phi');
M_.endo_names = char(M_.endo_names, 'b_e_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_e\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'b_e_obs');
M_.endo_names = char(M_.endo_names, 'bsp_F');
M_.endo_names_tex = char(M_.endo_names_tex, 'bsp\_F');
M_.endo_names_long = char(M_.endo_names_long, 'bsp_F');
M_.endo_names = char(M_.endo_names, 'bsp_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'bsp\_H');
M_.endo_names_long = char(M_.endo_names_long, 'bsp_H');
M_.endo_names = char(M_.endo_names, 'Y_net');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_net');
M_.endo_names_long = char(M_.endo_names_long, 'Y_net');
M_.endo_names = char(M_.endo_names, 'Y_net_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_net\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Y_net_obs');
M_.endo_names = char(M_.endo_names, 'Y_net_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_net\_2');
M_.endo_names_long = char(M_.endo_names_long, 'Y_net_2');
M_.endo_names = char(M_.endo_names, 'Y_net_2_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_net\_2\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Y_net_2_obs');
M_.endo_names = char(M_.endo_names, 'res_chk');
M_.endo_names_tex = char(M_.endo_names_tex, 'res\_chk');
M_.endo_names_long = char(M_.endo_names_long, 'res_chk');
M_.endo_names = char(M_.endo_names, 'deltaH');
M_.endo_names_tex = char(M_.endo_names_tex, 'deltaH');
M_.endo_names_long = char(M_.endo_names_long, 'deltaH');
M_.endo_names = char(M_.endo_names, 'deltaK');
M_.endo_names_tex = char(M_.endo_names_tex, 'deltaK');
M_.endo_names_long = char(M_.endo_names_long, 'deltaK');
M_.endo_names = char(M_.endo_names, 'GDP');
M_.endo_names_tex = char(M_.endo_names_tex, 'GDP');
M_.endo_names_long = char(M_.endo_names_long, 'GDP');
M_.endo_names = char(M_.endo_names, 'GDP_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'GDP\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'GDP_obs');
M_.endo_names = char(M_.endo_names, 'H_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'H\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'H_obs');
M_.endo_names = char(M_.endo_names, 'IH_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'IH\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'IH_obs');
M_.endo_names = char(M_.endo_names, 'res_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'res\_H');
M_.endo_names_long = char(M_.endo_names_long, 'res_H');
M_.endo_names = char(M_.endo_names, 'm_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'm\_e');
M_.endo_names_long = char(M_.endo_names_long, 'm_e');
M_.endo_names = char(M_.endo_names, 'm_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'm\_m');
M_.endo_names_long = char(M_.endo_names_long, 'm_m');
M_.endo_names = char(M_.endo_names, 'av_def');
M_.endo_names_tex = char(M_.endo_names_tex, 'av\_def');
M_.endo_names_long = char(M_.endo_names_long, 'av_def');
M_.endo_names = char(M_.endo_names, 'RDsp');
M_.endo_names_tex = char(M_.endo_names_tex, 'RDsp');
M_.endo_names_long = char(M_.endo_names_long, 'RDsp');
M_.endo_names = char(M_.endo_names, 'R_DD');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_DD');
M_.endo_names_long = char(M_.endo_names_long, 'R_DD');
M_.endo_names = char(M_.endo_names, 'W_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'W\_m');
M_.endo_names_long = char(M_.endo_names_long, 'W_m');
M_.endo_names = char(M_.endo_names, 'W_m_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'W\_m\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'W_m_obs');
M_.endo_names = char(M_.endo_names, 'b_tot');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_tot');
M_.endo_names_long = char(M_.endo_names_long, 'b_tot');
M_.endo_names = char(M_.endo_names, 'b_tot_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_tot\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'b_tot_obs');
M_.endo_names = char(M_.endo_names, 'C_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_b');
M_.endo_names_long = char(M_.endo_names_long, 'C_b');
M_.endo_names = char(M_.endo_names, 'C_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_e');
M_.endo_names_long = char(M_.endo_names_long, 'C_e');
M_.endo_names = char(M_.endo_names, 'A1');
M_.endo_names_tex = char(M_.endo_names_tex, 'A1');
M_.endo_names_long = char(M_.endo_names_long, 'A1');
M_.endo_names = char(M_.endo_names, 'B1');
M_.endo_names_tex = char(M_.endo_names_tex, 'B1');
M_.endo_names_long = char(M_.endo_names_long, 'B1');
M_.endo_names = char(M_.endo_names, 'C1');
M_.endo_names_tex = char(M_.endo_names_tex, 'C1');
M_.endo_names_long = char(M_.endo_names_long, 'C1');
M_.endo_names = char(M_.endo_names, 'D1');
M_.endo_names_tex = char(M_.endo_names_tex, 'D1');
M_.endo_names_long = char(M_.endo_names_long, 'D1');
M_.endo_names = char(M_.endo_names, 'R_mi');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_mi');
M_.endo_names_long = char(M_.endo_names_long, 'R_mi');
M_.endo_names = char(M_.endo_names, 'R_Fi');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_Fi');
M_.endo_names_long = char(M_.endo_names_long, 'R_Fi');
M_.endo_names = char(M_.endo_names, 'phib');
M_.endo_names_tex = char(M_.endo_names_tex, 'phib');
M_.endo_names_long = char(M_.endo_names_long, 'phib');
M_.endo_names = char(M_.endo_names, 'rho_F');
M_.endo_names_tex = char(M_.endo_names_tex, 'rho\_F');
M_.endo_names_long = char(M_.endo_names_long, 'rho_F');
M_.endo_names = char(M_.endo_names, 'rho_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'rho\_H');
M_.endo_names_long = char(M_.endo_names_long, 'rho_H');
M_.endo_names = char(M_.endo_names, 'rho_F_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'rho\_F\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'rho_F_obs');
M_.endo_names = char(M_.endo_names, 'rho_H_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'rho\_H\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'rho_H_obs');
M_.endo_names = char(M_.endo_names, 'DY_NET');
M_.endo_names_tex = char(M_.endo_names_tex, 'DY\_NET');
M_.endo_names_long = char(M_.endo_names_long, 'DY_NET');
M_.endo_names = char(M_.endo_names, 'DY_NET_OBS');
M_.endo_names_tex = char(M_.endo_names_tex, 'DY\_NET\_OBS');
M_.endo_names_long = char(M_.endo_names_long, 'DY_NET_OBS');
M_.endo_names = char(M_.endo_names, 'credit_gap_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'credit\_gap\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'credit_gap_obs');
M_.endo_names = char(M_.endo_names, 'bsp_H_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'bsp\_H\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'bsp_H_obs');
M_.endo_names = char(M_.endo_names, 'bsp_F_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'bsp\_F\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'bsp_F_obs');
M_.endo_names = char(M_.endo_names, 'dy_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'dy\_data');
M_.endo_names_long = char(M_.endo_names_long, 'dy_data');
M_.endo_names = char(M_.endo_names, 'dq_H_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'dq\_H\_data');
M_.endo_names_long = char(M_.endo_names_long, 'dq_H_data');
M_.endo_names = char(M_.endo_names, 'dbe_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'dbe\_data');
M_.endo_names_long = char(M_.endo_names_long, 'dbe_data');
M_.endo_names = char(M_.endo_names, 'dbm_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'dbm\_data');
M_.endo_names_long = char(M_.endo_names_long, 'dbm_data');
M_.endo_names = char(M_.endo_names, 'bank_rate_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'bank\_rate\_data');
M_.endo_names_long = char(M_.endo_names_long, 'bank_rate_data');
M_.endo_names = char(M_.endo_names, 'b_to_Y_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_to\_Y\_data');
M_.endo_names_long = char(M_.endo_names_long, 'b_to_Y_data');
M_.endo_names = char(M_.endo_names, 'd_b_to_Y_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'd\_b\_to\_Y\_data');
M_.endo_names_long = char(M_.endo_names_long, 'd_b_to_Y_data');
M_.endo_names = char(M_.endo_names, 'int_rate_HH_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'int\_rate\_HH\_data');
M_.endo_names_long = char(M_.endo_names_long, 'int_rate_HH_data');
M_.endo_names = char(M_.endo_names, 'bsp_H_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'bsp\_H\_data');
M_.endo_names_long = char(M_.endo_names_long, 'bsp_H_data');
M_.endo_names = char(M_.endo_names, 'bsp_F_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'bsp\_F\_data');
M_.endo_names_long = char(M_.endo_names_long, 'bsp_F_data');
M_.endo_names = char(M_.endo_names, 'dw_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'dw\_data');
M_.endo_names_long = char(M_.endo_names_long, 'dw_data');
M_.endo_names = char(M_.endo_names, 'dinve_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'dinve\_data');
M_.endo_names_long = char(M_.endo_names_long, 'dinve_data');
M_.endo_names = char(M_.endo_names, 'dc_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'dc\_data');
M_.endo_names_long = char(M_.endo_names_long, 'dc_data');
M_.endo_names = char(M_.endo_names, 'CR_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'CR\_data');
M_.endo_names_long = char(M_.endo_names_long, 'CR_data');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_255');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_255');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_255');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_329');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_329');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_329');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_283_0');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_283\_0');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_283_0');
M_.endo_partitions = struct();
M_.param_names = 'sigma_epsiHd';
M_.param_names_tex = 'sigma\_epsiHd';
M_.param_names_long = 'sigma_epsiHd';
M_.param_names = char(M_.param_names, 'sigma_epsiHk');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiHk');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiHk');
M_.param_names = char(M_.param_names, 'sigma_epsiA');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiA');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiA');
M_.param_names = char(M_.param_names, 'sigma_epsiJ');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiJ');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiJ');
M_.param_names = char(M_.param_names, 'sigma_epsiK');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiK');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiK');
M_.param_names = char(M_.param_names, 'sigma_epsiH');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiH');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiH');
M_.param_names = char(M_.param_names, 'sigma_epsiSe');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiSe');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiSe');
M_.param_names = char(M_.param_names, 'sigma_epsiSm');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiSm');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiSm');
M_.param_names = char(M_.param_names, 'sigma_epsiSF');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiSF');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiSF');
M_.param_names = char(M_.param_names, 'sigma_epsiSH');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiSH');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiSH');
M_.param_names = char(M_.param_names, 'sigma_epsiWb');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiWb');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiWb');
M_.param_names = char(M_.param_names, 'sigma_epsiRW');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiRW');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiRW');
M_.param_names = char(M_.param_names, 'sigma_epsiWe');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiWe');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiWe');
M_.param_names = char(M_.param_names, 'pp');
M_.param_names_tex = char(M_.param_names_tex, 'pp');
M_.param_names_long = char(M_.param_names_long, 'pp');
M_.param_names = char(M_.param_names, 'hab');
M_.param_names_tex = char(M_.param_names_tex, 'hab');
M_.param_names_long = char(M_.param_names_long, 'hab');
M_.param_names = char(M_.param_names, 'Cyphi_H');
M_.param_names_tex = char(M_.param_names_tex, 'Cyphi\_H');
M_.param_names_long = char(M_.param_names_long, 'Cyphi_H');
M_.param_names = char(M_.param_names, 'Cyphi_F');
M_.param_names_tex = char(M_.param_names_tex, 'Cyphi\_F');
M_.param_names_long = char(M_.param_names_long, 'Cyphi_F');
M_.param_names = char(M_.param_names, 'phi_Fs');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_Fs');
M_.param_names_long = char(M_.param_names_long, 'phi_Fs');
M_.param_names = char(M_.param_names, 'phi_Hs');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_Hs');
M_.param_names_long = char(M_.param_names_long, 'phi_Hs');
M_.param_names = char(M_.param_names, 'alphaa');
M_.param_names_tex = char(M_.param_names_tex, 'alphaa');
M_.param_names_long = char(M_.param_names_long, 'alphaa');
M_.param_names = char(M_.param_names, 'delta_K');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_K');
M_.param_names_long = char(M_.param_names_long, 'delta_K');
M_.param_names = char(M_.param_names, 'delta_H');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_H');
M_.param_names_long = char(M_.param_names_long, 'delta_H');
M_.param_names = char(M_.param_names, 'betta_m');
M_.param_names_tex = char(M_.param_names_tex, 'betta\_m');
M_.param_names_long = char(M_.param_names_long, 'betta_m');
M_.param_names = char(M_.param_names, 'betta_s');
M_.param_names_tex = char(M_.param_names_tex, 'betta\_s');
M_.param_names_long = char(M_.param_names_long, 'betta_s');
M_.param_names = char(M_.param_names, 'mu_m');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_m');
M_.param_names_long = char(M_.param_names_long, 'mu_m');
M_.param_names = char(M_.param_names, 'mu_e');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_e');
M_.param_names_long = char(M_.param_names_long, 'mu_e');
M_.param_names = char(M_.param_names, 'mu_F');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_F');
M_.param_names_long = char(M_.param_names_long, 'mu_F');
M_.param_names = char(M_.param_names, 'mu_H');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_H');
M_.param_names_long = char(M_.param_names_long, 'mu_H');
M_.param_names = char(M_.param_names, 'sigma_e1');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_e1');
M_.param_names_long = char(M_.param_names_long, 'sigma_e1');
M_.param_names = char(M_.param_names, 'sigma_m1');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_m1');
M_.param_names_long = char(M_.param_names_long, 'sigma_m1');
M_.param_names = char(M_.param_names, 'sigma_F');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_F');
M_.param_names_long = char(M_.param_names_long, 'sigma_F');
M_.param_names = char(M_.param_names, 'sigma_H');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_H');
M_.param_names_long = char(M_.param_names_long, 'sigma_H');
M_.param_names = char(M_.param_names, 'varphi_s');
M_.param_names_tex = char(M_.param_names_tex, 'varphi\_s');
M_.param_names_long = char(M_.param_names_long, 'varphi_s');
M_.param_names = char(M_.param_names, 'varphi_m');
M_.param_names_tex = char(M_.param_names_tex, 'varphi\_m');
M_.param_names_long = char(M_.param_names_long, 'varphi_m');
M_.param_names = char(M_.param_names, 'v_s');
M_.param_names_tex = char(M_.param_names_tex, 'v\_s');
M_.param_names_long = char(M_.param_names_long, 'v_s');
M_.param_names = char(M_.param_names, 'v_m');
M_.param_names_tex = char(M_.param_names_tex, 'v\_m');
M_.param_names_long = char(M_.param_names_long, 'v_m');
M_.param_names = char(M_.param_names, 'chi_b');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_b');
M_.param_names_long = char(M_.param_names_long, 'chi_b');
M_.param_names = char(M_.param_names, 'chi_e');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_e');
M_.param_names_long = char(M_.param_names_long, 'chi_e');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'a_e');
M_.param_names_tex = char(M_.param_names_tex, 'a\_e');
M_.param_names_long = char(M_.param_names_long, 'a_e');
M_.param_names = char(M_.param_names, 'a_s');
M_.param_names_tex = char(M_.param_names_tex, 'a\_s');
M_.param_names_long = char(M_.param_names_long, 'a_s');
M_.param_names = char(M_.param_names, 'a_b');
M_.param_names_tex = char(M_.param_names_tex, 'a\_b');
M_.param_names_long = char(M_.param_names_long, 'a_b');
M_.param_names = char(M_.param_names, 'psi_i');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_i');
M_.param_names_long = char(M_.param_names_long, 'psi_i');
M_.param_names = char(M_.param_names, 'psi_h');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_h');
M_.param_names_long = char(M_.param_names_long, 'psi_h');
M_.param_names = char(M_.param_names, 'rhoA');
M_.param_names_tex = char(M_.param_names_tex, 'rhoA');
M_.param_names_long = char(M_.param_names_long, 'rhoA');
M_.param_names = char(M_.param_names, 'rhoJ');
M_.param_names_tex = char(M_.param_names_tex, 'rhoJ');
M_.param_names_long = char(M_.param_names_long, 'rhoJ');
M_.param_names = char(M_.param_names, 'rhoK');
M_.param_names_tex = char(M_.param_names_tex, 'rhoK');
M_.param_names_long = char(M_.param_names_long, 'rhoK');
M_.param_names = char(M_.param_names, 'rhoH');
M_.param_names_tex = char(M_.param_names_tex, 'rhoH');
M_.param_names_long = char(M_.param_names_long, 'rhoH');
M_.param_names = char(M_.param_names, 'rhoSe');
M_.param_names_tex = char(M_.param_names_tex, 'rhoSe');
M_.param_names_long = char(M_.param_names_long, 'rhoSe');
M_.param_names = char(M_.param_names, 'rhoSm');
M_.param_names_tex = char(M_.param_names_tex, 'rhoSm');
M_.param_names_long = char(M_.param_names_long, 'rhoSm');
M_.param_names = char(M_.param_names, 'rhoSF');
M_.param_names_tex = char(M_.param_names_tex, 'rhoSF');
M_.param_names_long = char(M_.param_names_long, 'rhoSF');
M_.param_names = char(M_.param_names, 'rhoSH');
M_.param_names_tex = char(M_.param_names_tex, 'rhoSH');
M_.param_names_long = char(M_.param_names_long, 'rhoSH');
M_.param_names = char(M_.param_names, 'rhoWb');
M_.param_names_tex = char(M_.param_names_tex, 'rhoWb');
M_.param_names_long = char(M_.param_names_long, 'rhoWb');
M_.param_names = char(M_.param_names, 'rhoWe');
M_.param_names_tex = char(M_.param_names_tex, 'rhoWe');
M_.param_names_long = char(M_.param_names_long, 'rhoWe');
M_.param_names = char(M_.param_names, 'rhoHd');
M_.param_names_tex = char(M_.param_names_tex, 'rhoHd');
M_.param_names_long = char(M_.param_names_long, 'rhoHd');
M_.param_names = char(M_.param_names, 'rhoHk');
M_.param_names_tex = char(M_.param_names_tex, 'rhoHk');
M_.param_names_long = char(M_.param_names_long, 'rhoHk');
M_.param_names = char(M_.param_names, 'rhoRW');
M_.param_names_tex = char(M_.param_names_tex, 'rhoRW');
M_.param_names_long = char(M_.param_names_long, 'rhoRW');
M_.param_names = char(M_.param_names, 'zeta1');
M_.param_names_tex = char(M_.param_names_tex, 'zeta1');
M_.param_names_long = char(M_.param_names_long, 'zeta1');
M_.param_names = char(M_.param_names, 'zetae');
M_.param_names_tex = char(M_.param_names_tex, 'zetae');
M_.param_names_long = char(M_.param_names_long, 'zetae');
M_.param_names = char(M_.param_names, 'epsilonH1s');
M_.param_names_tex = char(M_.param_names_tex, 'epsilonH1s');
M_.param_names_long = char(M_.param_names_long, 'epsilonH1s');
M_.param_names = char(M_.param_names, 'epsilonF1s');
M_.param_names_tex = char(M_.param_names_tex, 'epsilonF1s');
M_.param_names_long = char(M_.param_names_long, 'epsilonF1s');
M_.param_names = char(M_.param_names, 'tau');
M_.param_names_tex = char(M_.param_names_tex, 'tau');
M_.param_names_long = char(M_.param_names_long, 'tau');
M_.param_names = char(M_.param_names, 'taue');
M_.param_names_tex = char(M_.param_names_tex, 'taue');
M_.param_names_long = char(M_.param_names_long, 'taue');
M_.param_names = char(M_.param_names, 'rp');
M_.param_names_tex = char(M_.param_names_tex, 'rp');
M_.param_names_long = char(M_.param_names_long, 'rp');
M_.param_names = char(M_.param_names, 'rpe');
M_.param_names_tex = char(M_.param_names_tex, 'rpe');
M_.param_names_long = char(M_.param_names_long, 'rpe');
M_.param_names = char(M_.param_names, 'phiinf1');
M_.param_names_tex = char(M_.param_names_tex, 'phiinf1');
M_.param_names_long = char(M_.param_names_long, 'phiinf1');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'nu');
M_.param_names_tex = char(M_.param_names_tex, 'nu');
M_.param_names_long = char(M_.param_names_long, 'nu');
M_.param_names = char(M_.param_names, 'psib');
M_.param_names_tex = char(M_.param_names_tex, 'psib');
M_.param_names_long = char(M_.param_names_long, 'psib');
M_.param_names = char(M_.param_names, 'phis');
M_.param_names_tex = char(M_.param_names_tex, 'phis');
M_.param_names_long = char(M_.param_names_long, 'phis');
M_.param_names = char(M_.param_names, 'LTVHrule');
M_.param_names_tex = char(M_.param_names_tex, 'LTVHrule');
M_.param_names_long = char(M_.param_names_long, 'LTVHrule');
M_.param_names = char(M_.param_names, 'LTVFrule');
M_.param_names_tex = char(M_.param_names_tex, 'LTVFrule');
M_.param_names_long = char(M_.param_names_long, 'LTVFrule');
M_.param_names = char(M_.param_names, 'gamma_y');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_y');
M_.param_names_long = char(M_.param_names_long, 'gamma_y');
M_.param_names = char(M_.param_names, 'gamma_w');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_w');
M_.param_names_long = char(M_.param_names_long, 'gamma_w');
M_.param_names = char(M_.param_names, 'gamma_inve');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_inve');
M_.param_names_long = char(M_.param_names_long, 'gamma_inve');
M_.param_names = char(M_.param_names, 'gamma_c');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_c');
M_.param_names_long = char(M_.param_names_long, 'gamma_c');
M_.param_names = char(M_.param_names, 'gamma_db');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_db');
M_.param_names_long = char(M_.param_names_long, 'gamma_db');
M_.param_names = char(M_.param_names, 'gamma_bspH');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_bspH');
M_.param_names_long = char(M_.param_names_long, 'gamma_bspH');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 13;
M_.endo_nbr = 196;
M_.param_nbr = 78;
M_.orig_endo_nbr = 193;
M_.aux_vars(1).endo_index = 194;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 195;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 196;
M_.aux_vars(3).type = 3;
M_.aux_vars(3).orig_index = 13;
M_.aux_vars(3).orig_lead_lag = 0;
options_.varobs = cell(1);
options_.varobs(1)  = {'dy_data'};
options_.varobs(2)  = {'dq_H_data'};
options_.varobs(3)  = {'int_rate_HH_data'};
options_.varobs(4)  = {'bank_rate_data'};
options_.varobs(5)  = {'bsp_H_data'};
options_.varobs(6)  = {'dw_data'};
options_.varobs(7)  = {'dinve_data'};
options_.varobs(8)  = {'dbm_data'};
options_.varobs(9)  = {'dc_data'};
options_.varobs_id = [ 180 181 187 184 188 190 191 183 192  ];
M_.Sigma_e = zeros(13, 13);
M_.Correlation_matrix = eye(13, 13);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('LTV1_static');
erase_compiled_function('LTV1_dynamic');
M_.orig_eq_nbr = 193;
M_.eq_nbr = 196;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 50 0;
 0 51 0;
 0 52 246;
 2 53 247;
 0 54 0;
 3 55 0;
 4 56 0;
 0 57 0;
 5 58 0;
 6 59 0;
 7 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 8 65 0;
 9 66 0;
 0 67 248;
 0 68 0;
 0 69 249;
 0 70 250;
 0 71 251;
 0 72 252;
 0 73 0;
 0 74 253;
 0 75 254;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 255;
 0 86 256;
 10 87 0;
 11 88 0;
 12 89 0;
 13 90 257;
 14 91 0;
 0 92 0;
 0 93 0;
 0 94 0;
 0 95 258;
 0 96 259;
 0 97 0;
 15 98 0;
 0 99 260;
 0 100 0;
 0 101 0;
 0 102 261;
 0 103 0;
 16 104 262;
 17 105 263;
 18 106 0;
 19 107 0;
 0 108 264;
 0 109 0;
 0 110 265;
 20 111 266;
 0 112 267;
 0 113 268;
 0 114 0;
 0 115 0;
 0 116 0;
 0 117 0;
 0 118 0;
 0 119 0;
 0 120 0;
 0 121 0;
 0 122 269;
 0 123 0;
 0 124 270;
 0 125 0;
 0 126 0;
 0 127 0;
 0 128 0;
 0 129 0;
 0 130 0;
 0 131 0;
 0 132 0;
 0 133 271;
 0 134 0;
 21 135 0;
 22 136 0;
 0 137 0;
 0 138 272;
 0 139 0;
 0 140 0;
 0 141 0;
 0 142 0;
 0 143 0;
 0 144 0;
 0 145 0;
 0 146 0;
 23 147 0;
 24 148 0;
 0 149 0;
 0 150 0;
 0 151 0;
 25 152 0;
 0 153 0;
 0 154 0;
 0 155 0;
 0 156 0;
 0 157 0;
 0 158 0;
 26 159 0;
 0 160 0;
 0 161 0;
 0 162 0;
 0 163 0;
 0 164 0;
 0 165 0;
 27 166 0;
 0 167 0;
 0 168 0;
 0 169 273;
 0 170 274;
 0 171 0;
 0 172 0;
 28 173 0;
 29 174 0;
 30 175 0;
 31 176 0;
 32 177 0;
 33 178 0;
 34 179 0;
 35 180 0;
 36 181 0;
 37 182 0;
 38 183 0;
 39 184 0;
 40 185 0;
 0 186 0;
 41 187 0;
 0 188 0;
 0 189 0;
 42 190 0;
 43 191 0;
 0 192 0;
 0 193 0;
 0 194 0;
 0 195 275;
 44 196 0;
 0 197 0;
 0 198 0;
 0 199 0;
 0 200 0;
 0 201 0;
 0 202 0;
 0 203 0;
 0 204 0;
 0 205 0;
 0 206 276;
 0 207 0;
 0 208 0;
 0 209 0;
 0 210 0;
 0 211 0;
 0 212 0;
 0 213 277;
 0 214 278;
 0 215 279;
 0 216 280;
 0 217 0;
 0 218 0;
 0 219 0;
 0 220 0;
 0 221 0;
 0 222 0;
 0 223 0;
 0 224 0;
 0 225 0;
 45 226 0;
 0 227 0;
 46 228 0;
 0 229 0;
 0 230 0;
 0 231 0;
 0 232 0;
 0 233 0;
 47 234 0;
 0 235 0;
 0 236 0;
 0 237 0;
 48 238 0;
 0 239 0;
 0 240 0;
 0 241 0;
 0 242 0;
 0 243 281;
 0 244 282;
 49 245 0;]';
M_.nstatic = 115;
M_.nfwrd   = 32;
M_.npred   = 44;
M_.nboth   = 5;
M_.nsfwrd   = 37;
M_.nspred   = 49;
M_.ndynamic   = 81;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:13];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(196, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(13, 1);
M_.params = NaN(78, 1);
M_.NNZDerivatives = [749; -1; -1];
load LTV1_parameter_values.mat;
M_.params( 1 ) = set_sigma_epsiHd;
sigma_epsiHd = M_.params( 1 );
M_.params( 2 ) = set_sigma_epsiHk;
sigma_epsiHk = M_.params( 2 );
M_.params( 3 ) = set_sigma_epsiA;
sigma_epsiA = M_.params( 3 );
M_.params( 4 ) = set_sigma_epsiJ;
sigma_epsiJ = M_.params( 4 );
M_.params( 5 ) = set_sigma_epsiK;
sigma_epsiK = M_.params( 5 );
M_.params( 6 ) = set_sigma_epsiH;
sigma_epsiH = M_.params( 6 );
M_.params( 7 ) = set_sigma_epsiSe;
sigma_epsiSe = M_.params( 7 );
M_.params( 8 ) = set_sigma_epsiSm;
sigma_epsiSm = M_.params( 8 );
M_.params( 9 ) = set_sigma_epsiSF;
sigma_epsiSF = M_.params( 9 );
M_.params( 10 ) = set_sigma_epsiSH;
sigma_epsiSH = M_.params( 10 );
M_.params( 11 ) = set_sigma_epsiWb;
sigma_epsiWb = M_.params( 11 );
M_.params( 12 ) = set_sigma_epsiRW;
sigma_epsiRW = M_.params( 12 );
M_.params( 13 ) = set_sigma_epsiWe;
sigma_epsiWe = M_.params( 13 );
sigma_epsilon_phi=set_sigma_epsilon_phi;
M_.params( 14 ) = set_pp;
pp = M_.params( 14 );
M_.params( 24 ) = set_betta_s;
betta_s = M_.params( 24 );
M_.params( 23 ) = set_betta_m;
betta_m = M_.params( 23 );
M_.params( 15 ) = set_hab;
hab = M_.params( 15 );
M_.params( 16 ) = set_Cyphi_H;
Cyphi_H = M_.params( 16 );
M_.params( 19 ) = set_phi_Hs;
phi_Hs = M_.params( 19 );
M_.params( 17 ) = set_Cyphi_F;
Cyphi_F = M_.params( 17 );
M_.params( 18 ) = set_phi_Fs;
phi_Fs = M_.params( 18 );
M_.params( 20 ) = set_alphaa;
alphaa = M_.params( 20 );
M_.params( 64 ) = set_rp;
rp = M_.params( 64 );
M_.params( 65 ) = set_rpe;
rpe = M_.params( 65 );
M_.params( 21 ) = set_delta_K;
delta_K = M_.params( 21 );
M_.params( 22 ) = set_delta_H;
delta_H = M_.params( 22 );
M_.params( 25 ) = set_mu_m;
mu_m = M_.params( 25 );
M_.params( 26 ) = set_mu_e;
mu_e = M_.params( 26 );
M_.params( 27 ) = set_mu_F;
mu_F = M_.params( 27 );
M_.params( 28 ) = set_mu_H;
mu_H = M_.params( 28 );
M_.params( 29 ) = set_sigma_e1;
sigma_e1 = M_.params( 29 );
M_.params( 30 ) = set_sigma_m1;
sigma_m1 = M_.params( 30 );
M_.params( 31 ) = set_sigma_F;
sigma_F = M_.params( 31 );
M_.params( 32 ) = set_sigma_H;
sigma_H = M_.params( 32 );
M_.params( 33 ) = set_varphi_s;
varphi_s = M_.params( 33 );
M_.params( 34 ) = set_varphi_m;
varphi_m = M_.params( 34 );
M_.params( 35 ) = set_v_s;
v_s = M_.params( 35 );
M_.params( 36 ) = set_v_m;
v_m = M_.params( 36 );
M_.params( 37 ) = set_chi_b;
chi_b = M_.params( 37 );
M_.params( 38 ) = set_chi_e;
chi_e = M_.params( 38 );
M_.params( 39 ) = set_eta;
eta = M_.params( 39 );
M_.params( 40 ) = set_a_e;
a_e = M_.params( 40 );
M_.params( 41 ) = set_a_s;
a_s = M_.params( 41 );
M_.params( 42 ) = set_a_b;
a_b = M_.params( 42 );
M_.params( 43 ) = set_psi_i;
psi_i = M_.params( 43 );
M_.params( 44 ) = set_psi_h;
psi_h = M_.params( 44 );
M_.params( 45 ) = set_rhoA;
rhoA = M_.params( 45 );
M_.params( 46 ) = set_rhoJ;
rhoJ = M_.params( 46 );
M_.params( 47 ) = set_rhoK;
rhoK = M_.params( 47 );
M_.params( 49 ) = set_rhoSe;
rhoSe = M_.params( 49 );
M_.params( 50 ) = set_rhoSm;
rhoSm = M_.params( 50 );
M_.params( 51 ) = set_rhoSF;
rhoSF = M_.params( 51 );
M_.params( 52 ) = set_rhoSH;
rhoSH = M_.params( 52 );
M_.params( 53 ) = set_rhoWb;
rhoWb = M_.params( 53 );
M_.params( 54 ) = set_rhoWe;
rhoWe = M_.params( 54 );
M_.params( 55 ) = set_rhoHd;
rhoHd = M_.params( 55 );
M_.params( 48 ) = set_rhoH;
rhoH = M_.params( 48 );
M_.params( 56 ) = set_rhoHk;
rhoHk = M_.params( 56 );
M_.params( 57 ) = set_rhoRW;
rhoRW = M_.params( 57 );
M_.params( 58 ) = set_zeta1;
zeta1 = M_.params( 58 );
M_.params( 59 ) = set_zetae;
zetae = M_.params( 59 );
M_.params( 60 ) = set_epsilonH1s;
epsilonH1s = M_.params( 60 );
M_.params( 61 ) = set_epsilonF1s;
epsilonF1s = M_.params( 61 );
M_.params( 62 ) = set_tau;
tau = M_.params( 62 );
M_.params( 63 ) = set_taue;
taue = M_.params( 63 );
M_.params( 66 ) = set_phiinf1;
phiinf1 = M_.params( 66 );
M_.params( 67 ) = set_kappa;
kappa = M_.params( 67 );
M_.params( 68 ) = set_nu;
nu = M_.params( 68 );
M_.params( 69 ) = set_psib;
psib = M_.params( 69 );
M_.params( 70 ) = set_phis;
phis = M_.params( 70 );
M_.params( 71 ) = set_LTVHrule;
LTVHrule = M_.params( 71 );
M_.params( 72 ) = set_LTVFrule;
LTVFrule = M_.params( 72 );
M_.params( 73 ) = set_gamma_y;
gamma_y = M_.params( 73 );
M_.params( 74 ) = set_gamma_w;
gamma_w = M_.params( 74 );
M_.params( 75 ) = set_gamma_inve;
gamma_inve = M_.params( 75 );
M_.params( 76 ) = set_gamma_c;
gamma_c = M_.params( 76 );
M_.params( 77 ) = set_gamma_db;
gamma_db = M_.params( 77 );
M_.params( 78 ) = set_gamma_bspH;
gamma_bspH = M_.params( 78 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(3);
M_.Sigma_e(2, 2) = M_.params(4);
M_.Sigma_e(3, 3) = M_.params(5);
M_.Sigma_e(4, 4) = M_.params(7);
M_.Sigma_e(5, 5) = M_.params(8);
M_.Sigma_e(6, 6) = M_.params(9);
M_.Sigma_e(7, 7) = M_.params(10);
M_.Sigma_e(8, 8) = M_.params(11);
M_.Sigma_e(9, 9) = M_.params(13);
M_.Sigma_e(10, 10) = M_.params(10);
M_.Sigma_e(11, 11) = M_.params(1);
M_.Sigma_e(12, 12) = M_.params(2);
estim_params_.var_exo = [];
estim_params_.var_endo = [];
estim_params_.corrx = [];
estim_params_.corrn = [];
estim_params_.param_vals = [];
estim_params_.param_vals = [estim_params_.param_vals; 23, 0.9842, 0.95, 0.99, 1, 0.97, 0.005, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 64, 0.035, 0, 1, 1, 0.05, 0.025, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 65, 0.04, 0, 1, 1, 0.05, 0.025, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, 0.01, 0, 1, 1, 0.05, 0.025, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.03, 0, 1, 1, 0.05, 0.025, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, 0.1, 0.01, 1, 1, 0.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, 0.273, 0, 1, 1, 0.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 73, 0.21, 1e-6, 5, 5, 0, 5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 74, 0.8, 1e-6, 5, 5, 0, 5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 75, 0.17, 1e-6, 5, 5, 0, 5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 76, 0.24, 1e-6, 5, 5, 0, 5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.4167, 0.2, 0.99, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 43, 1.4340, 1, 5, 3, 2, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 44, 4.9446, 1, 5, 3, 2, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, 1.2989, 0, 5, 3, 1, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, 0.7290, 0, 5, 3, 1, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, 0.318, 1e-5, 1, 5, 5, 2.88675134595, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, 0.1, 1e-5, 1, 5, 5, 2.88675134595, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 31, 0.0363, 1e-5, 1, 5, 5, 2.88675134595, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, 0.0363, 1e-5, 1, 5, 5, 2.88675134595, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 0.3, 0, 1, 1, 0.3, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, 0.3, 0, 1, 1, 0.3, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, 0.3, 0, 1, 1, 0.3, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, 0.3, 0, 1, 1, 0.3, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, 0.3, 0, 1, 1, 0.3, 0.05, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 11, 0.1, 0, 99, 5, 5, 2.88675134595, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 12, 0.01, 0, 99, 5, 5, 2.88675134595, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.1, 0, 99, 5, 5, 2.88675134595, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.1, 0, 99, 5, 5, 2.88675134595, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.1, 0, 99, 5, 5, 2.88675134595, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.1, 0, 99, 5, 5, 2.88675134595, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.1, 0, 99, 5, 5, 2.88675134595, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.1, 0, 99, 5, 5, 2.88675134595, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.1, 0, 99, 5, 5, 2.88675134595, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, 0.1, 0, 99, 5, 5, 2.88675134595, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, 0.1, 0, 99, 5, 5, 2.88675134595, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 55, 0.01, 0, 0.9999, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 56, 0.01, 0, 0.9999, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 45, 0.01, 0, 0.9999, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 46, 0.01, 0, 0.9999, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 47, 0.01, 0, 0.9999, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 49, 0.01, 0, 0.9999, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 50, 0.01, 0, 0.99, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 51, 0.01, 0, 0.99, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 52, 0.01, 0, 0.99, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 54, 0.01, 0, 0.99, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 53, 0.01, 0, 0.99, 1, 0.5, 0.2, NaN, NaN, NaN ];
options_.kalman_algo = 4;
options_.mh_drop = 0.2;
options_.mh_jscale = 0.28;
options_.mh_nblck = 1;
options_.mh_replic = 0;
options_.mode_compute = 0;
options_.nodiagnostic = 1;
options_.nograph = 1;
options_.presample = 2;
options_.datafile = 'estimation_dataset_quarterly.mat';
options_.mode_file = 'LTV1_mode.mat';
options_.optim_opt = '''TolFun'',1e-5,''TolX'',1e-5,''Display'',''iter'',''MaxIter'',1000,''Hessian'',''bfgs''';
options_.first_obs = 2;
options_.nobs = 75;
options_.order = 1;
var_list_ = char();
oo_recursive_=dynare_estimation(var_list_);
options_.drop = 5000;
options_.irf = 40;
options_.nograph = 1;
options_.order = 1;
options_.periods = 10000;
var_list_ = char();
info = stoch_simul(var_list_);
save('LTV1_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('LTV1_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('LTV1_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('LTV1_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('LTV1_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('LTV1_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('LTV1_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
